algoritmo "QualOSeuNome"
// Disciplina   : Algoritmos
// Professor   : Gustavo Guanabara
// Descrição   : a que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela:
// Autor(a)    : Camille dos Santos Nogueira
// Data atual  : 03/05/2023
   Nome: Caractere
inicio
    Escreva ("Qual é o seu nome? ")
    Leia (Nome)
    EscrevaL ("Olá, ", Nome, " é um prazer te conhecer!")

fimalgoritmo